# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb45209a8db2a9f26b084db0bbebe5af9a44009d4d18b94b11d523c1ad8175474700a6066fecf86acfa402767c02f0365e4215d1bcf51e84bf09e2d5d8686ca

test:
  secret_key_base: 4e35c9dd179c6562f63c860b4c5037ad44b624d893f8dbe9737448fcad5754caf492fe97f706e95c149246855d36ea8b2ad2ed7ef9a2aad345fc9e82656a8546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
